apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kneipolympics-deployment
  name: kneipolympics-deployment
  namespace: kneipolympics
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kneipolympics-deployment
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: kneipolympics-deployment
    spec:
      containers:
        - image: ghcr.io/pesca-dev/kneipolympics:fd7183178feb7d92010e330bda3aa20b90ac0a8b
          imagePullPolicy: Always
          name: aoc-website-deployment
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
