name: Update Image Reference

on:
  repository_dispatch:
    types: kneipolympics-deploy-trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v2
      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"
      - name: Update Version In Checked-Out Code
        if: ${{ github.event.client_payload.sha }}
        run: |
          sed -i "s@\(.*image:\).*@\1 ghcr.io/${{ env.OWNER_LC }}/kneipolympics:${{ github.event.client_payload.sha }}@" ${GITHUB_WORKSPACE}/manifests/deployment.yml
      - name: Commit The New Image Reference
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.event.client_payload.sha }}
        with:
          commit_message: Deploy new image ${{ github.event.client_payload.sha }}
          branch: main
          commit_options: "--no-verify --signoff"
          repository: .
          commit_user_name: PescaDev GitOps Bot
          commit_user_email: gitops@pesca.dev
          commit_author: PescaDev GitOps <gitops@pesca.dev>
